# Change this to your credentials (take a look at the source code if you are suspicious at that point. which is understandable)

SUDO_PW: ""
USER_NAME: ""
USER_PW: ""

# The connected public ipv4 address visible from the outside.
# This is there to check if a connection was established. Or if you are already connected to the vpn via another ürpces.

VPN_PUB_IP: ""


